import{a as w,S as q,i}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="50728089-41b308bdec84da4d1a4e6886f",B="https://pixabay.com/api/",E=15;async function f(t,r=1){return(await w.get(B,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:E}})).data}let M=new q(".gallery a");const m=document.querySelector(".gallery"),d=document.querySelector(".loader");function h(t){const r=t.map(({webformatURL:s,largeImageURL:c,tags:e,likes:o,views:n,comments:S,downloads:v})=>`<li class="gallery-item">
          <a href="${c}">
            <img src="${s}" alt="${e}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${o}</p>
            <p><b>Views:</b> ${n}</p>
            <p><b>Comments:</b> ${S}</p>
            <p><b>Downloads:</b> ${v}</p>
          </div>
        </li>`).join("");m.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){m.innerHTML=""}function y(){d&&d.classList.remove("is-hidden")}function p(){d&&d.classList.add("is-hidden")}function g(){const t=document.querySelector(".load-more-btn");t&&t.classList.remove("is-hidden")}function b(){const t=document.querySelector(".load-more-btn");t&&t.classList.add("is-hidden")}const L=document.querySelector(".form"),O=L.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more-btn");let a=1,l="",u=0;L.addEventListener("submit",async t=>{if(t.preventDefault(),l=O.value.trim(),!l){i.warning({message:"Please enter a search term!"});return}a=1,$(),b(),y();try{const r=await f(l,a);u=r.totalHits,r.hits.length===0?i.info({message:"Sorry, no images match your search."}):(h(r.hits),r.hits.length<u&&g())}catch{i.error({message:"Error fetching images."})}finally{p()}});x.addEventListener("click",async()=>{a+=1,y(),b();try{const t=await f(l,a);h(t.hits);const r=Math.ceil(u/15);a<r?g():i.info({message:"We're sorry, but you've reached the end of search results."});const{height:s}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}catch{i.error({message:"Error fetching more images."})}finally{p()}});
//# sourceMappingURL=index.js.map
