import{a as P,S as q,i}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const E="50728089-41b308bdec84da4d1a4e6886f",B="https://pixabay.com/api/",M=15;async function u(o,t=1){return(await P.get(B,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:M}})).data}let $=new q(".gallery a");const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");function p(o){const t=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:r,views:n,comments:w,downloads:S})=>`<li class="gallery-item">
          <a href="${c}">
            <img src="${s}" alt="${e}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${r}</p>
            <p><b>Views:</b> ${n}</p>
            <p><b>Comments:</b> ${w}</p>
            <p><b>Downloads:</b> ${S}</p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function O(){f.innerHTML=""}function y(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}const v=document.querySelector(".form"),x=v.querySelector('input[name="search-text"]'),A=document.querySelector(".load-more");let a=1,l="",d=0;v.addEventListener("submit",async o=>{if(o.preventDefault(),l=x.value.trim(),!l){i.warning({message:"Please enter a search term!"});return}a=1,O(),L(),y();try{const t=await u(l,a);d=t.totalHits,t.hits.length===0?i.info({message:"Sorry, no images match your search."}):(p(t.hits),t.hits.length<d&&b())}catch{i.error({message:"Error fetching images."})}finally{g()}});A.addEventListener("click",async()=>{a+=1,y(),L();try{const o=await u(l,a);p(o.hits);const t=Math.ceil(d/15);a<t?b():i.info({message:"We're sorry, but you've reached the end of search results."});const{height:s}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}catch{i.error({message:"Error fetching more images."})}finally{g()}});
//# sourceMappingURL=index.js.map
